
version: '3.5'

services:
  app:
    container_name: app_container
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8090:8090"
    volumes:
      - .:/code
    depends_on:
      - pg_db
    command: 
      [ "dev" ]
    networks:
      - default

  pg_db:
    container_name: pg_db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=restapi_dev
    volumes:
       - postgres:/data/postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - default
    restart: unless-stopped
  
  # pgadmin:
  #   container_name: pgadmin_app
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   volumes:
  #      - pgadmin:/var/lib/pgadmin

  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"
  #   networks:
  #     - default
  #   restart: unless-stopped

networks:
  default:
    external:
      name: external-app


volumes:
    postgres:
    pgadmin: